### ISSUE TITLE
Tombo unrecognized arguments: --genome-fasta, --motif-descriptions 

### ISSUE THREAD

**Issue by kwonej0617** [zhongzhd/ont_m6a_detection#2]
Hello. 
After successfully installing Tombo, I gave a try to run Tombo based on your script in m6A_detection/Tombo.sh. However, I got this error message as follows,
````
tombo: error: unrecognized arguments: --genome-fasta reference/Homo_sapiens.GRCh38.cdna.ncrna_wtChrIs_modified.fa --motif-descriptions RRACH:3:m6A
````
Here is the part where the error came from.
````
#output statistical results
tombo text_output browser_files --fast5-basedirs ${wt_fast5} --statistics-filename wt.tombo.stats --browser-file-basename wt_rrach --genome-fasta ${ref} --motif-descriptions RRACH:3:m6A --file-types coverage dampened_fraction fraction --corrected-group RawGenomeCorrected_00
````
Could you please help me figure out why I got this message?

Thank you!

**Comment by zhongzhd** [comment]
Can you please provide more complete details of the scripts you have run? You can run "tombo text_output browser_files -h" to see all arguments, and "--genome-fasta" and "--motif-descriptions" are both included.

**Comment by kwonej0617** [comment]
Hi, @zhongzhd 
That was because I used Tombo v1.4 which doesn't have --genome-fastq and motif-descriptions options in tombo text_output browser_files. After installing Tombo 1.5 it worked! 
Thank you.
